// ===== SAMPLE SCHEMA =====

function SampleSchema() {
  updateXsdType('xs');
  document.getElementById('radio_xs').checked = true;
  var textarea = document.getElementById("schema-text");
  textarea.value = ''
+ '<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">\n'
+ '  <xs:element name="Library">\n'
+ '    <xs:annotation>\n'
+ '      <xs:documentation>Root node</xs:documentation>\n'
+ '    </xs:annotation>\n'
+ '      <xs:complexType>\n'
+ '        <xs:sequence>\n'
+ '          <xs:element name="Name">\n'
+ '            <xs:annotation>\n'
+ '              <xs:documentation>Name of library</xs:documentation>\n'
+ '            </xs:annotation>\n'
+ '            <xs:simpleType>\n'
+ '            <xs:restriction base="xs:string">\n'
+ '              <xs:minLength value="1"/>\n'
+ '              <xs:maxLength value="256"/>\n'
+ '            </xs:restriction>\n'
+ '          </xs:simpleType>\n'
+ '        </xs:element>\n'
+ '        <xs:element name="Address" type="AddressType">\n'
+ '          <xs:annotation>\n'
+ '            <xs:documentation>Address details of library like city name, ZIP code, street name and phone number</xs:documentation>\n'
+ '          </xs:annotation>\n'
+ '        </xs:element>\n'
+ '        <xs:element name="OpeningHours" minOccurs="0">\n'
+ '          <xs:annotation>\n'
+ '            <xs:documentation>Opening hours of library</xs:documentation>\n'
+ '          </xs:annotation>\n'
+ '          <xs:complexType>\n'
+ '            <xs:sequence>\n'
+ '              <xs:element name="Monday" type="OpenTimeType" minOccurs="0"/>\n'
+ '              <xs:element name="Tuesday" type="OpenTimeType" minOccurs="0"/>\n'
+ '              <xs:element name="Wednesday" type="OpenTimeType" minOccurs="0"/>\n'
+ '              <xs:element name="Thursday" type="OpenTimeType" minOccurs="0"/>\n'
+ '              <xs:element name="Friday" type="OpenTimeType" minOccurs="0"/>\n'
+ '              <xs:element name="Saturday" type="OpenTimeType" minOccurs="0"/>\n'
+ '              <xs:element name="Sunday" type="OpenTimeType" minOccurs="0"/>\n'
+ '            </xs:sequence>\n'
+ '          </xs:complexType>\n'
+ '        </xs:element>\n'
+ '        <xs:element name="ExistingSince" type="xs:date" minOccurs="0">\n'
+ '          <xs:annotation>\n'
+ '            <xs:documentation>Library existing since</xs:documentation>\n'
+ '          </xs:annotation>\n'
+ '        </xs:element>\n'
+ '        <xs:element name="Book" type="BookType" maxOccurs="unbounded">\n'
+ '          <xs:annotation>\n'
+ '            <xs:documentation>List of books available at library</xs:documentation>\n'
+ '          </xs:annotation>\n'
+ '        </xs:element>\n'
+ '        <xs:element name="CreationDate" type="xs:date">\n'
+ '          <xs:annotation>\n'
+ '            <xs:documentation>Creation date of this data set</xs:documentation>\n'
+ '          </xs:annotation>\n'
+ '        </xs:element>\n'
+ '      </xs:sequence>\n'
+ '    </xs:complexType>\n'
+ '  </xs:element>\n'
+ '  <xs:complexType name="OpenTimeType">\n'
+ '    <xs:sequence>\n'
+ '      <xs:element name="From" type="xs:time"/>\n'
+ '      <xs:element name="To" type="xs:time"/>\n'
+ '    </xs:sequence>\n'
+ '  </xs:complexType>\n'
+ '  <xs:complexType name="BookType">\n'
+ '    <xs:sequence>\n'
+ '      <xs:element name="Author"><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="Publisher"><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="Published" type="xs:date" minOccurs="0"/>\n'
+ '      <xs:element name="Language" type="xs:language"/>\n'
+ '      <xs:element name="Titel"><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="Subtitle" minOccurs="0"><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="ISBN" minOccurs="0"><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="32"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="Pages" type="xs:positiveInteger" minOccurs="0"/>\n'
+ '    </xs:sequence>\n'
+ '  </xs:complexType>\n'
+ '  <xs:complexType name="AddressType">\n'
+ '    <xs:sequence>\n'
+ '      <xs:element name="Country" minOccurs="0"><xs:annotation><xs:documentation>Country of library</xs:documentation></xs:annotation><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="CityName" minOccurs="0"><xs:annotation><xs:documentation>City name of library address</xs:documentation></xs:annotation><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="ZIP" type="xs:positiveInteger" minOccurs="0"><xs:annotation><xs:documentation>ZIP code of library address</xs:documentation></xs:annotation></xs:element>\n'
+ '      <xs:element name="Street" minOccurs="0"><xs:annotation><xs:documentation>Street of library address</xs:documentation></xs:annotation><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="Phone" minOccurs="0"><xs:annotation><xs:documentation>Phone number of library</xs:documentation></xs:annotation><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="128"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '      <xs:element name="Homepage" minOccurs="0"><xs:annotation><xs:documentation>Homepage of library (URL)</xs:documentation></xs:annotation><xs:simpleType><xs:restriction base="xs:string"><xs:maxLength value="256"/></xs:restriction></xs:simpleType></xs:element>\n'
+ '    </xs:sequence>\n'
+ '  </xs:complexType>\n'
+ '</xs:schema>';
}
